# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Majorizor_EM <- function(sig_til, sig, S, tau) {
    .Call(`_CompStratDesign_Majorizor_EM`, sig_til, sig, S, tau)
}

Majorizor_EM_grad <- function(sig_til, sig, S, tau) {
    .Call(`_CompStratDesign_Majorizor_EM_grad`, sig_til, sig, S, tau)
}

Majorizor_linear <- function(sig_til, sig, S) {
    .Call(`_CompStratDesign_Majorizor_linear`, sig_til, sig, S)
}

Majorizor_linear_grad <- function(sig_til, sig, S) {
    .Call(`_CompStratDesign_Majorizor_linear_grad`, sig_til, sig, S)
}

c_prox <- function(S, G, lambda, maxiter, tol, verbose) {
    .Call(`_CompStratDesign_c_prox`, S, G, lambda, maxiter, tol, verbose)
}

c_ggb_psd <- function(S, G, lambda, delta, maxiter, tol, verbose) {
    .Call(`_CompStratDesign_c_ggb_psd`, S, G, lambda, delta, maxiter, tol, verbose)
}

c_ggb_mm_linear <- function(S, sig_til, G, lambda, tau, t, B, maxiter, tol, verbose) {
    .Call(`_CompStratDesign_c_ggb_mm_linear`, S, sig_til, G, lambda, tau, t, B, maxiter, tol, verbose)
}

c_ggb_mm_EM <- function(S, sig_til, G, lambda, tau, t, B, maxiter, tol, verbose) {
    .Call(`_CompStratDesign_c_ggb_mm_EM`, S, sig_til, G, lambda, tau, t, B, maxiter, tol, verbose)
}

