# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EstimateCov <- function(data, lambda) {
    .Call(`_CompStratDesign_EstimateCov`, data, lambda)
}

bcd_method <- function(S, G, lambda, penalty, maxiter = 500L, tol = 1e-4, verbose = 1L) {
    .Call(`_CompStratDesign_bcd_method`, S, G, lambda, penalty, maxiter, tol, verbose)
}

iter_method <- function(S, G, t, tol, B, maxiter, lambda, objective_vec, ggb_maxiter = 500L, ggb_tol = 1e-4, verbose = 1L) {
    .Call(`_CompStratDesign_iter_method`, S, G, t, tol, B, maxiter, lambda, objective_vec, ggb_maxiter, ggb_tol, verbose)
}

